//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAroundTheWorld.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class COMPETITIONEntities : DbContext
    {
        public COMPETITIONEntities()
            : base("name=COMPETITIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANSWER> ANSWERs { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<CompetitionEntry> CompetitionEntries { get; set; }
        public virtual DbSet<CompetitionQuestion> CompetitionQuestions { get; set; }
        public virtual DbSet<School> Schools { get; set; }
    
        public virtual ObjectResult<GetAnswers_Result> GetAnswers(Nullable<int> pQUESTION_ID)
        {
            var pQUESTION_IDParameter = pQUESTION_ID.HasValue ?
                new ObjectParameter("pQUESTION_ID", pQUESTION_ID) :
                new ObjectParameter("pQUESTION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAnswers_Result>("GetAnswers", pQUESTION_IDParameter);
        }
    
        public virtual ObjectResult<GetQuestion_Result> GetQuestion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQuestion_Result>("GetQuestion");
        }
    
        public virtual ObjectResult<string> GetSuggestion(string pSearch)
        {
            var pSearchParameter = pSearch != null ?
                new ObjectParameter("pSearch", pSearch) :
                new ObjectParameter("pSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetSuggestion", pSearchParameter);
        }
    
        public virtual int SetUpQuestions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetUpQuestions");
        }
    }
}
