//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAroundTheWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.CompetitionEntries = new HashSet<CompetitionEntry>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string TELEPHONE { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual ICollection<CompetitionEntry> CompetitionEntries { get; set; }
    }
}
